### ISSUE TITLE
Files exist but it says they do not?

### ISSUE THREAD

**Issue by niftylettuce** [ckarlbe/postcss-font-base64#5]
I think this is due to `format("eot")` being in the font face declaration

Example output from console:

```sh
app/controllers/../../ODelI1aHBYDBqgeIAH2zlN0tugusXa58UbOrParLRF0.eot formateot,../../ODelI1aHBYDBqgeIAH2zlNV_2ngZ8dMf8fLgjYEouxg.woff2 formatwoff2,../../ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff does not exist.
```

Example css declaration:

```css
@font-face{
  font-family: "Source Code Pro";
  font-style: normal;
  font-weight: 900;
  src: local("Source Code Pro Black"),local(SourceCodePro-Black),url(../../leqv3v-yTsJNC7nFznSMqSDZg7i-e40o9FYYiSpZxAc.eot) format("eot"),url(../../leqv3v-yTsJNC7nFznSMqXZhYM0_6AejPZE-OqA592o.woff2) format("woff2"),url(../../leqv3v-yTsJNC7nFznSMqXiec-hVyr2k4iOzEQsW1iE.woff) format("woff"); }
```
