### ISSUE TITLE
Fails on multiple source urls

### ISSUE THREAD

**Issue by philliphartin** [ckarlbe/postcss-font-base64#7]
When using multiple URLs in a font-faces source I am unable to compile.

**Example Input**
```
@font-face {
  font-family: "TolyerNo1";
  src: url("../fonts/TolyerNo1Regular.woff2") format("woff2"), url("../fonts/TolyerNo1Regular.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}
```

**Error in Output**
`61% building modules 428/429 modules 1 active ...emes/project-x/src/css/base.css undefined 'does not exist.' `

No matter what files I use the src, woff2, woff, eot, ttf etc, they all fail if more than one url is used.

**Comment by delicatesther** [comment]
I encountered the same issue. Also; I am rendering my font URL's dynamically (I'm creating an iconfont using [icon-font-generator](https://github.com/Workshape/icon-font-generator#readme)), which outputs the font sources with a parameter to prevent caching, so for example:

```css
@font-face {
    font-family: "icons";
    src: url("./fonts/icons.ttf?2adda561745340dbaac30079d9841ace") format("truetype");
}
```

Unfortunately, this declaration is then completely skipped in the postcss process.
